version: "3.11"

services:

# application service
  bot-app:
    container_name: ${APP_NAME}
    build: .
    command: python run.py
    volumes:
      - .:/app
    restart: always
    networks:
      - custom
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  custom:
    driver: bridge